## 27/04/2016 : Shiny User Interface
library(RColorBrewer)


## Organisation de la page
shinyUI(fluidPage(
  headerPanel(HTML("aweSOM")),
  
  tabsetPanel(
    #### Panel 'Welcome, Import Data'
    #########################################################################
    tabPanel("Import Data", 
             includeHTML("js/lodash.min.js"),
             includeHTML("js/d3.min.js"),
             includeHTML("js/hexbin.js"),
             includeHTML("js/svg_todataurl.js"),
             includeHTML("js/rgbcolor.js"),
             includeHTML("js/canvg.js"),
             includeHTML("js/box.js"),
             includeHTML("js/radar-chart-d3.js"),
             includeHTML("js/word-cloud.js"),
             
             h2("Import your data"), 
             fluidRow(
               column(4,
                      wellPanel(
                        fileInput('dataFile', 'Choose CSV/TXT File'),
                        HTML("<b>Import parameters</b>"),
                        checkboxInput('header', ' Header?', TRUE), 
                        fluidRow(column(4, p('Separator:')), 
                                 column(8, selectInput('sep', NULL,
                                                       c("Comma ','","Semicolon ';'","Tab","Space"), 
                                                       "Comma ','"))),
                        fluidRow(column(4, p('Quote:')), 
                                 column(8, selectInput('quote', NULL,
                                                       c("None","Double Quote \"","Single Quote '"), 
                                                       'Double Quote "'))),
                        fluidRow(column(4, p('Decimal mark')), 
                                 column(8, selectInput('dec', NULL, 
                                                       c("Period '.'", "Comma ','"),
                                                       "Period '.'")))
                        )),
               column(8, 
                      uiOutput("dataImportMessage"), 
                      dataTableOutput("dataView")))),
    tabPanel("Train", 
             wellPanel(fluidRow(column(2, h3("Map info:")),
                                column(10, verbatimTextOutput("Message")))),

             fluidRow(column(4, wellPanel(actionButton("trainbutton", "Train Self-organizing Map"), 
                                          h3("Training options:"),
                                          fluidRow(column(4, p("Map size (rows,columns)")), 
                                                   column(4, numericInput('kohDimx', NULL, 4, min= 1)), 
                                                   column(4, numericInput('kohDimy', NULL, 4, min= 1))),
                                          checkboxInput("trainscale", "Scale training data", T), 
                                          checkboxInput("trainAdvanced", "Advanced options", F), 
                                          conditionalPanel("input.trainAdvanced", 
                                                           fluidRow(column(4, p("Topology")), 
                                                                    column(8, selectInput('kohTopo', NULL, 
                                                                                          c("hexagonal", "rectangular")))),
                                                           fluidRow(column(4, p("Initialization")), 
                                                                    column(8, selectInput("kohInit", NULL, 
                                                                                          c("PCA"= "pca", "PCA Obs"= "pca.sample", 
                                                                                            "Random Obs"= "random")))),
                                                           fluidRow(column(4, p("rlen")), 
                                                                    column(8, numericInput("trainRlen", NULL, 100, 1, 1e6))),
                                                           fluidRow(column(4, p("Alpha (start,stop)")), 
                                                                    column(4, numericInput("trainAlpha1", NULL, .05, 1e-6, 1e3)), 
                                                                    column(4, numericInput("trainAlpha2", NULL, .01, 1e-6, 1e3))),
                                                           fluidRow(column(4, p("Radius (start,stop)")), 
                                                                    column(4, numericInput("trainRadius1", NULL, .05, 1e-6, 1e3)), 
                                                                    column(4, numericInput("trainRadius2", NULL, .05, 1e-6, 1e3)))))),
                      column(8, 
                             h3("Training variables:"),
                             fluidRow(column(4, actionButton("varNum", "Select numeric variables")), 
                                      column(4, actionButton("varAll", "Select all variables")), 
                                      column(4, actionButton("varNone", "Unselect all variables"))),
                             p(),
                             fluidRow(column(1, HTML("<p><b>Use</b></p>")), 
                                      column(2, HTML("<p><b>Weight</b></p>")), 
                                      column(9, HTML("<p><b>Name</b></p>"))),
                             uiOutput("trainVarOptions")))),

    tabPanel("Graph", 
             fluidRow(column(4, 
                             ## Sélection du graphique et des variables
                             h4("Graph options"),
                             fluidRow(column(4, p("Graph type:")), 
                                      column(8, selectInput("graphType", NULL, 
                                                            choices= c("Superclass Dendrogram"= "Dendrogram",
                                                                       "Superclass Scree plot"= "Screeplot",
                                                                       "Population map"= "Hitmap", 
                                                                       "Radar"= "Radar", 
                                                                       "Barplot"= "Barplot", 
                                                                       "Boxplot"= "Boxplot",
                                                                       "Line"= "Line", 
                                                                       # "Star"= "Star", 
                                                                       "Heat"= "Color", 
                                                                       "Pie"= "Camembert", 
                                                                       # "Names"= "Names", 
                                                                       "Neighbour distance"= "UMatrix"), 
                                                            selected= "Hitmap"))),
                             conditionalPanel('input.graphType == "Camembert" | input.graphType == "Color" | input.graphType == "Names"', 
                                              uiOutput("plotVarOne")),
                             conditionalPanel(paste0('input.graphType == "Radar" | ', 
                                                     'input.graphType == "Line" | ', 
                                                     'input.graphType == "Barplot" | ', 
                                                     'input.graphType == "Boxplot" | ', 
                                                     'input.graphType == "Star"'), 
                                              uiOutput("plotVarMult")),
                             uiOutput("plotNames"),
                             checkboxInput("plotAdvanced", "Advanced options", F),
                             conditionalPanel("input.plotAdvanced", 
                                              h4("Advanced options"),
                                              conditionalPanel(paste0('input.graphType == "Radar" | ', 
                                                                      'input.graphType == "Line" | ', 
                                                                      'input.graphType == "Barplot" | ', 
                                                                      'input.graphType == "Color" | ', 
                                                                      'input.graphType == "UMatrix" | ', 
                                                                      'input.graphType == "Star"'), 
                                                               checkboxInput("contrast", "Enhanced contrast", value= T)), 
                                              conditionalPanel('input.graphType == "Boxplot"', 
                                                               checkboxInput("plotOutliers", "Plot outliers", value= T)),
                                              conditionalPanel('input.graphType != "Color"', 
                                                               fluidRow(column(4, p("Superclass palette")),
                                                                        column(8, selectInput("palsc", NULL, 
                                                                           c("viridis", "grey", "rainbow", "heat", "terrain", 
                                                                             "topo", "cm", rownames(brewer.pal.info)), 
                                                                           "Set3")))),
                                              fluidRow(column(4, p("Plots palette")),
                                                       column(8,selectInput("palplot", NULL, 
                                                          c("viridis", "grey", "rainbow", "heat", "terrain", 
                                                            "topo", "cm", rownames(brewer.pal.info)), 
                                                          "viridis")))),
                             uiOutput("plotWarning")), 
                             
                      column(8, 
                             fluidRow(column(2, p("Plot size:")), 
                                      column(4, sliderInput("plotSize", NULL, 10, 1000, value= 100)), 
                                      column(2, p("Nb. superclasses:")), 
                                      column(4, numericInput('kohSuperclass', NULL, 2, min= 1))),
                             ## Pour afficher seulement le graphique choisi :
                             conditionalPanel('input.graphType == "Dendrogram"', 
                                              plotOutput("plotDendrogram")),
                             conditionalPanel('input.graphType == "Screeplot"', 
                                              plotOutput("plotScreeplot")),
                             conditionalPanel('input.graphType != "Dendrogram" & input.graphType != "Screeplot"', 
                                              includeHTML("graphs.html"), 
                                              HTML('<h4 id="cell-info">Hover over the plot for information.</h4>'),
                                              HTML('<h4 id="plot-message">-</h4>'),
                                              HTML('<div id="thePlot" class="shiny-Plot"><svg /></div>'), 
                                              HTML('<br />'), 
                                              wellPanel(HTML('<p id="plot-names">Observation names will appear here.</p>')))
                             ))), 
    tabPanel("Clustered data", 
             h4("Original data, SOM cells, and superclasses."),
             fluidRow(
               column(4,
                      downloadButton("clustDownload", "Download (csv file)"),
                      h4("Selected variables"),
                      uiOutput("clustVariables")),
               column(8, dataTableOutput("clustTable"))))
  )
))
