## 27/04/2016 : Shiny User Interface
library(RColorBrewer)


## Organisation de la page
shinyUI(fluidPage(
  headerPanel(HTML("Kohcorico")),
  
  tabsetPanel(
    #### Panel 'Welcome, Import Data'
    #########################################################################
    tabPanel("Import Data", 
             includeHTML("js/lodash.min.js"),
             includeHTML("js/d3.min.js"),
             includeHTML("js/hexbin.js"),
             includeHTML("js/svg_todataurl.js"),
             includeHTML("js/rgbcolor.js"),
             includeHTML("js/canvg.js"),
             includeHTML("js/box.js"),
             includeHTML("js/radar-chart-d3.js"),
             includeHTML("js/word-cloud.js"),
             
             h2("Import your data"), 
             h4("Set the import parameters so that the data table appears correctly."),
             fluidRow(
               column(4,
                      wellPanel(
                        fileInput('file1', 'Choose CSV/TXT File'),
                        fluidRow(column(6, checkboxInput('header', ' Header?', TRUE)), 
                                 column(6, checkboxInput('rownames', ' Row names?', FALSE))), 
                        selectInput('sep', 'Separator:',
                                    c("Comma ','","Semicolon ';'","Tab","Space"), 
                                    "Comma ','"),
                        selectInput('quote', 'Quote:',
                                    c("None","Double Quote \"","Single Quote '"), 
                                    'Double Quote "'),
                        selectInput('dec', 'Decimal mark', 
                                    c("Period '.'", "Comma ','"),
                                    "Period '.'"),
                        helpText("Note: The preview only shows a restricted
                                 number of observations, the full set is imported."))),
               column(8,
                      fluidRow(
                        column(2, p('Nb. rows preview:')),
                        column(4, numericInput('nrow.preview', NULL, 20)), 
                        column(2, p('Nb. cols preview:')),
                        column(4, numericInput('ncol.preview', NULL, 10))),
                      uiOutput("rownames.col"),
                      tableOutput("view"))
               )), 
    
    tabPanel("Train", 
             wellPanel(fluidRow(column(2, h3("Map info:")),
                                column(10, verbatimTextOutput("Message")))),
             fluidRow(column(12, actionButton("trainbutton", "Train"))),
             h3("Training options:"),
             fluidRow(column(4, 
                             fluidRow(column(4, p("Map size (rows,columns)")), 
                                      column(4, numericInput('kohDimx', NULL, 4, min= 1)), 
                                      column(4, numericInput('kohDimy', NULL, 4, min= 1))),
                             checkboxInput("trainscale", "Scale training data", T), 
                             checkboxInput("trainAdvanced", "Advanced options", F), 
                             conditionalPanel("input.trainAdvanced", 
                                              fluidRow(column(4, p("Topology")), 
                                                       column(8, selectInput('kohTopo', NULL, 
                                                                             c("hexagonal", "rectangular")))),
                                              fluidRow(column(4, p("Initialization")), 
                                                       column(8, selectInput("kohInit", NULL, 
                                                                             c("PCA"= "pca", "PCA Obs"= "pca.sample", 
                                                                               "Random Obs"= "random")))),
                                              fluidRow(column(4, p("rlen")), 
                                                       column(8, numericInput("trainRlen", NULL, 100, 1, 1e6))),
                                              fluidRow(column(4, p("Alpha (start, stop)")), 
                                                       column(4, numericInput("trainAlpha1", NULL, .05, 1e-6, 1e3)), 
                                                       column(4, numericInput("trainAlpha2", NULL, .01, 1e-6, 1e3))),
                                              fluidRow(column(4, p("Radius (start, stop)")), 
                                                       column(4, numericInput("trainRadius1", NULL, .05, 1e-6, 1e3)), 
                                                       column(4, numericInput("trainRadius2", NULL, .05, 1e-6, 1e3))))),
                      column(8, 
                             fluidRow(column(4, actionButton("varNum", "Select numeric variables")), 
                                      column(4, actionButton("varAll", "Select all variables")), 
                                      column(4, actionButton("varNone", "Unselect all variables"))), 
                             uiOutput("varchoice")))),
    
    tabPanel("Graph", 
             fluidRow(column(4, 
                             ## Sélection du graphique et des variables
                             h4("Graph options"),
                             fluidRow(column(4, p("Graph type:")), 
                                      column(8, selectInput("graphType", NULL, 
                                                            choices= c("Superclass Dendrogram"= "Dendrogram", 
                                                                       "Population map"= "Hitmap", 
                                                                       "Radar"= "Radar", 
                                                                       "Barplot"= "Barplot", 
                                                                       "Boxplot"= "Boxplot",
                                                                       "Line"= "Line", 
                                                                       "Star"= "Star", 
                                                                       "Heat"= "Color", 
                                                                       "Pie"= "Camembert", 
                                                                       "Names"= "Names"), 
                                                            selected= "Hitmap"))),
                             conditionalPanel('input.graphType == "Camembert" | input.graphType == "Color" | input.graphType == "Names"', 
                                              uiOutput("plotVarOne")),
                             conditionalPanel(paste0('input.graphType == "Radar" | ', 
                                                     'input.graphType == "Line" | ', 
                                                     'input.graphType == "Barplot" | ', 
                                                     'input.graphType == "Boxplot" | ', 
                                                     'input.graphType == "Star"'), 
                                              uiOutput("plotVarMult")),
                             uiOutput("plotNames"),
                             checkboxInput("plotAdvanced", "Advanced options", F),
                             conditionalPanel("input.plotAdvanced", 
                                              h4("Advanced options"),
                                              conditionalPanel(paste0('input.graphType == "Radar" | ', 
                                                                      'input.graphType == "Line" | ', 
                                                                      'input.graphType == "Barplot" | ', 
                                                                      'input.graphType == "Color" | ', 
                                                                      'input.graphType == "Star"'), 
                                                               checkboxInput("contrast", "Enhanced contrast", value= T)), 
                                              conditionalPanel('input.graphType != "Color"', 
                                                               fluidRow(column(4, p("Superclass palette")),
                                                                        column(8, selectInput("palsc", NULL, 
                                                                           c("viridis", "rainbow", "heat", "terrain", 
                                                                             "topo", "cm", rownames(brewer.pal.info)), 
                                                                           "Set3")))),
                                              fluidRow(column(4, p("Plots palette")),
                                                       column(8,selectInput("palplot", NULL, 
                                                          c("viridis", "rainbow", "heat", "terrain", 
                                                            "topo", "cm", rownames(brewer.pal.info)), 
                                                          "viridis")))),
                             uiOutput("plotWarning")), 
                             
                      column(8, 
                             fluidRow(column(2, p("Plot size:")), 
                                      column(4, sliderInput("plotSize", NULL, 10, 1000, value= 100)), 
                                      column(2, p("Nb. superclasses:")), 
                                      column(4, numericInput('kohSuperclass', NULL, 2, min= 1))),
                             ## Pour afficher seulement le graphique choisi :
                             conditionalPanel('input.graphType == "Dendrogram"', 
                                              plotOutput("screeplot")),
                             conditionalPanel('input.graphType != "Dendrogram"', 
                                              includeHTML("graphs.html"), 
                                              HTML('<h4 id="cell-info">Hover over the plot for information.</h4>'),
                                              HTML('<h4 id="plot-message">-</h4>'),
                                              HTML('<div id="thePlot" class="shiny-Plot"><svg /></div>'), 
                                              HTML('<br />'), 
                                              wellPanel(HTML('<p id="plot-names">Observation names will appear here.</p>')))
                             )))
  )
  
))
