## 27/04/2016 : Shiny User Interface
# library(RColorBrewer)

## Organisation de la page
shinyUI(fluidPage(
  headerPanel(HTML("aweSOM")),
  
  tabsetPanel(
    #### Panel 'Welcome, Import Data'
    #########################################################################
    tabPanel("Import Data", 
             includeHTML("js/lodash.min.js"),
             includeHTML("js/d3.min.js"),
             includeHTML("js/hexbin.js"),
             includeHTML("js/svg_todataurl.js"),
             includeHTML("js/rgbcolor.js"),
             includeHTML("js/canvg.js"),
             includeHTML("js/box.js"),
             includeHTML("js/radar-chart-d3.js"),
             includeHTML("js/word-cloud.js"),
             
             h2("Import your data"), 
             fluidRow(
               column(4,
                      wellPanel(
                        fileInput('dataFile', 'Choose CSV/TXT File'),
                        HTML("<b>Import parameters</b>"),
                        fluidRow(column(4, p('Header:')), 
                                 column(8, selectInput('header', NULL,
                                                       c("Auto", "Header",
                                                         "No Header"), 
                                                       "Auto"))),
                        fluidRow(column(4, p('Separator:')), 
                                 column(8, selectInput('sep', NULL,
                                                       c("Auto", "Comma ','",
                                                         "Semicolon ';'",
                                                         "Tab","Space"), 
                                                       "Auto"))),
                        fluidRow(column(4, p('Quote:')), 
                                 column(8, selectInput('quote', NULL,
                                                       c("None","Double Quote \"","Single Quote '"), 
                                                       'Double Quote "'))),
                        fluidRow(column(4, p('Decimal mark')), 
                                 column(8, selectInput('dec', NULL, 
                                                       c("Period '.'", "Comma ','"),
                                                       "Period '.'")))
                        )),
               column(8, 
                      uiOutput("dataImportMessage"), 
                      DT::dataTableOutput("dataView")))),
    tabPanel("Train", 
             wellPanel(fluidRow(column(2, h3("Map info:")),
                                column(10, verbatimTextOutput("Message")))),

             fluidRow(column(4, wellPanel( 
                 h3("Train new map:"),
                 actionButton("trainbutton", "Train Self-organizing Map"), 
                 fluidRow(column(4, p("Map size (rows,columns)")), 
                          column(4, numericInput('kohDimx', NULL, 4, min= 1)), 
                          column(4, numericInput('kohDimy', NULL, 4, min= 1))),
                 checkboxInput("trainscale", "Scale training data", T), 
                 checkboxInput("trainAdvanced", "Advanced options", F), 
                 conditionalPanel("input.trainAdvanced", 
                                  fluidRow(column(4, p("Topology")), 
                                           column(8, selectInput('kohTopo', NULL, 
                                                                 c("hexagonal", "rectangular")))),
                                  fluidRow(column(4, p("Initialization")), 
                                           column(8, selectInput("kohInit", NULL, 
                                                                 c("PCA"= "pca", "PCA Obs"= "pca.sample", 
                                                                   "Random Obs"= "random")))),
                                  fluidRow(column(4, p("rlen")), 
                                           column(8, numericInput("trainRlen", NULL, 100, 1, 1e6))),
                                  fluidRow(column(4, p("Alpha (start,stop)")), 
                                           column(4, numericInput("trainAlpha1", NULL, .05, 1e-6, 1e3)), 
                                           column(4, numericInput("trainAlpha2", NULL, .01, 1e-6, 1e3))),
                                  fluidRow(column(4, p("Radius (start,stop)")), 
                                           column(4, numericInput("trainRadius1", NULL, .05, 1e-6, 1e3)), 
                                           column(4, numericInput("trainRadius2", NULL, .05, 1e-6, 1e3))), 
                                  fluidRow(column(4, p("Random seed:")), 
                                           column(8, numericInput("trainSeed", NULL, sample(1e5, 1), 1, 1e9)))))), 
                 
                 # wellPanel(
                 #   h3("Import SOM:"),
                 #   fileInput("importmapbutton", "Import (RDS)"))),
               column(8, 
                      h3("Training variables:"),
                      fluidRow(column(4, actionButton("varNum", "Select numeric variables")), 
                               column(4, actionButton("varAll", "Select all variables")), 
                               column(4, actionButton("varNone", "Unselect all variables"))),
                      p(),
                      fluidRow(column(2, HTML("<p><b>Weight</b></p>")), 
                               column(8, HTML("<p><b>Variable</b></p>")), 
                               column(2, HTML("<p><b>Type</b></p>"))),
                      uiOutput("trainVarOptions")))),
    
    tabPanel("Graph", 
             fluidRow(column(4, 
                             ## Sélection du graphique et des variables
                             h4("Graph options"),
                             fluidRow(column(4, p("Plot:")), 
                                      column(8, selectInput("graphWhat", NULL, 
                                                            choices= c("Map Information"= "MapInfo",
                                                                       "Numeric Variables"= "Numeric",
                                                                       "Categorical Variables"= "Categorical"), 
                                                            selected= "MapInfo"))),
                             fluidRow(column(4, p("Graph type:")), 
                                      column(8, selectInput("graphType", NULL, 
                                                            choices= c("Population map"= "Hitmap",
                                                                       "Superclass Dendrogram"= "Dendrogram",
                                                                       "Superclass Scree plot"= "Screeplot",
                                                                       "Neighbour distance"= "UMatrix", 
                                                                       "Smooth distance"= "SmoothDist", 
                                                                       "Abstraction"= "Abstraction"), 
                                                            selected= "Hitmap"))),
                             conditionalPanel('input.graphType == "Camembert" | input.graphType == "CatBarplot" | input.graphType == "Color" | input.graphType == "Names"', 
                                              uiOutput("plotVarOne")),
                             conditionalPanel(paste0('input.graphType == "Radar" | ', 
                                                     'input.graphType == "Line" | ', 
                                                     'input.graphType == "Barplot" | ', 
                                                     'input.graphType == "Boxplot" | ', 
                                                     'input.graphType == "Star"'), 
                                              uiOutput("plotVarMult")),
                             conditionalPanel('input.graphType != "Dendrogram" & input.graphType != "Screeplot" & input.graphType != "SmoothDist" & input.graphType != "Abstraction"',
                                              uiOutput("plotNames")),
                             checkboxInput("plotAdvanced", "Advanced options", F),
                             conditionalPanel("input.plotAdvanced", 
                                              h4("Advanced options"),
                                              conditionalPanel(paste0('input.graphType == "CatBarplot" | ', 
                                                                      'input.graphType == "Radar" | ', 
                                                                      'input.graphType == "Line" | ', 
                                                                      'input.graphType == "Barplot" | ', 
                                                                      'input.graphType == "Color" | ', 
                                                                      'input.graphType == "UMatrix" | ', 
                                                                      'input.graphType == "Star"'), 
                                                               checkboxInput("contrast", "Enhanced contrast", value= T)), 
                                              conditionalPanel('input.graphType == "Boxplot"', 
                                                               checkboxInput("plotOutliers", "Plot outliers", value= T)),
                                              conditionalPanel('input.graphType != "Color" & input.graphType != "UMatrix" & input.graphType != "SmoothDist"', 
                                                               fluidRow(column(4, p("Superclass palette")),
                                                                        column(8, selectInput("palsc", NULL, 
                                                                           c("viridis", "grey", "rainbow", "heat", "terrain", 
                                                                             "topo", "cm", rownames(RColorBrewer::brewer.pal.info)), 
                                                                           "Set3")))),
                                              fluidRow(column(4, p("Plots palette")),
                                                       column(8,selectInput("palplot", NULL, 
                                                          c("viridis", "grey", "rainbow", "heat", "terrain", 
                                                            "topo", "cm", rownames(RColorBrewer::brewer.pal.info)), 
                                                          "viridis"))), 
                                              checkboxInput("plotRevPal", "Reverse palette"), 
                                              conditionalPanel('input.graphType == "Camembert"', 
                                                               checkboxInput("plotEqualSize", "Equal pie sizes", F)), 
                                              conditionalPanel('input.graphType == "Abstraction"', 
                                                               numericInput("plotAbstrCutoff", "Links cut-off", 
                                                                            min= 0, max= 1, step = .01, value= 0))),
                             uiOutput("plotWarning")), 
                             
                      column(8, 
                             fluidRow(column(2, p("Plot size:")), 
                                      column(4, sliderInput("plotSize", NULL, 10, 1000, value= 100)), 
                                      column(2, p("Nb. superclasses:")), 
                                      column(4, numericInput('kohSuperclass', NULL, 2, min= 1))),
                             ## Pour afficher seulement le graphique choisi :
                             conditionalPanel('input.graphType == "Dendrogram"', 
                                              plotOutput("plotDendrogram")),
                             conditionalPanel('input.graphType == "Screeplot"', 
                                              plotOutput("plotScreeplot")),
                             conditionalPanel('input.graphType == "SmoothDist"', 
                                              plotOutput("plotSmoothDist")),
                             conditionalPanel('input.graphType == "Abstraction"', 
                                              plotOutput("plotAbstraction")),
                                              # plotly::plotlyOutput("plotAbstraction")),
                             
                             conditionalPanel('input.graphType != "Dendrogram" & input.graphType != "Screeplot" & input.graphType != "SmoothDist" & input.graphType != "Abstraction"', 
                                              includeHTML("graphs.html"), 
                                              HTML('<h4 id="cell-info">Hover over the plot for information.</h4>'),
                                              HTML('<h4 id="plot-message">-</h4>'),
                                              HTML('<div id="thePlot" class="shiny-Plot"><svg /></div>'), 
                                              HTML('<br />'), 
                                              wellPanel(HTML('<p id="plot-names">Observation names will appear here.</p>')))
                             ))), 
    tabPanel("Clustered data", 
             
             fluidRow(
               
               column(4,
                      h3("Download full map"),
                      downloadButton("somDownload", "Download SOM (rds file)"),
                      h3("Download data, SOM cells, and superclasses."),
                      downloadButton("clustDownload", "Download Clustering (csv file)"),
                      h4("Selected variables"),
                      fluidRow(column(4, actionButton("clustSelectNone", "Unselect all")), 
                               column(4, actionButton("clustSelectTrain", "Select train")), 
                               column(4, actionButton("clustSelectAll", "Select all"))),
                      uiOutput("clustVariables")),
               column(8, DT::dataTableOutput("clustTable")))), 
    tabPanel("Reproducible code", 
             verbatimTextOutput("codeTxt"))
  )
))
